### ISSUE TITLE
Replace Black Box term with Opaque or similar neutral terms

### ISSUE THREAD

**Issue by AsadBinImtiaz** [logicalclocks/maggy#71]
The terms black box / white box are seen borderline racist by many due to common perception of black being used for something negative and white with something good. The racist implications of such terms are not always clear, and there is rarely consensus. It may be however better to avoid and replace such terms with more neutral language. It is therefore requested to use more neutral terminology instead of such oppressive language.
Lets replace:
- blacklist / whitelist -> blocklist / allowlist
- master / slave to leader / worker
- white/black box -> clear/opaque or closed/glass box
- whitespace -> Emptyspace

The term black box appears:
- line 54 of setup.py
- line 7 of README.rst
- line 64/66 of maggy/experiment.py
- line 33 of maggy/optimizer/bayes/base.py

**Comment by moritzmeister** [comment]
Closing this, the term "Black Box" is well established in the research community, which I personally perceive as very diverse and representative, and to this point the term had no connection to race or anything the like.
